.TH tcosxmlrpc 1 "Jun 19, 2006" "tcosxmlrpc man page"

.SH NAME
tcosxmlrpc \- TCOS XML-RPC server

.SH SYNOPSIS
.B tcosxmlrpc
.RI [ options ]
.br

.SH DESCRIPTION

This manpage show options for 
.B tcosxmlrpc
server.

.PP
\fBtcosxmlrpc\fP is a small xmlrpc server that listen xmlrpc connections
from TcosMonitor and allow to exec, or scan status of thin clients.

.SH OPTIONS
.B
.IP /path/to/abyss.conf
Path (relative or absolute) to a well formated abyss.conf file

.B
.IP TCOS_DEBUG
Set TCOS_DEBUG=1 to see debug output

.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Homepage: http://www.tcosproject.org

.SH SEE ALSO
tcos.conf(5)

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
