.TH tcosmd5 1 "Jun 21, 2006" "tcosmd5 man page"

.SH NAME
tcosmd5 \- TCOS util to show md5 of a passed string

.SH SYNOPSIS
.B tcosmd5
.RI [ options ]
.br

.SH DESCRIPTION

This manpage show options for 
.B tcosmd5
server.

.PP
\fBtcosmd5\fP is a small C app that create md5 of an string passed
from cmdline.

.SH OPTIONS
.B
.IP string
string to show his md5


.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Homepage: http://www.tcosproject.org

.SH SEE ALSO
tcos.conf(5)

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
