.TH tcosmd5 1 "Jun 21, 2006" "tcosmd5 man page"

.SH NAME
update-tcospasswd \- TCOS util to generate crypt TCOS passwords files

.SH SYNOPSIS
.B update-tcospasswd
.br

.SH DESCRIPTION

This manpage show options for 
.B update-tcospasswd
script.

.PP
\fBupdate-tcospasswd\fP is a small shell script that create TCOS crypt 
password files with some questions.


.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Homepage: http://www.tcosproject.org

.SH SEE ALSO
tcos.conf(5)

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
