#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac


# change timeout in usplash start
if [ -e /dev/.initramfs/usplash_fifo ]; then
    /sbin/usplash_write "TIMEOUT 180" > /dev/null 2>&1 || true
fi
