#!/bin/sh

PREREQ="usplash"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac


# change timeout in usplash start
if [ -e /dev/.initramfs/usplash_fifo ]; then
  log_begin_msg "Change usplash timeout"
    /sbin/usplash_write "TIMEOUT 180" || true
  log_end_msg
fi
