0008
TCOS Thin Client Operating System.
More available command line options

02 allmodules       07 Download all kernel modules (exec gentcos -allmodules)
02 showmodules      07 Pause boot and show loaded and needed modules
02 wifi             07 Enable wireless connection (need essid)
02 essid=foo        07 Set wireless ESSID to connect to
02 nbd              07 Enable NBD squashfs
02 nbdport=xxx      07 Port to use NBS (default 2000)
02 sshuser=xxx      07 User of SSHX
02 sshhost=xxx      07 Host IP of SSHX
02 sshport=xxx      07 SSH port of SSHX
02 sshdesktop=xxx   07 ssh desktop of SSHX
                   (startkde, gnome-session, startxfce4)

02 noswap           07 disable swap file creation (swap part is used always)
02 forcenfs         07 Use NFS (no check for memory)

Press 02F107 to more help or 08F1007 to return to main screen

