0008
TCOS Thin Client Operating System.
Available command line options

02 server=foo      07 IP address of all services server (def DHCP server)
02 xserver=foo     07 IP address of XDMCP server (def DHCP server)
02 tftpserver=foo  07 IP address of TFTPD server (def DHCP server)
02 fontserver=foo  07 IP address of TFTPD server (def DHCP server)
02 nfsserver=foo   07 IP address of TFTPD server (def DHCP server)
02 rdesktop=foo    07 IP address of Windows Terminal Server (def DHCP)
02 startx=X        07 set default X session 
                  (R=remote L=local N=none W=windows F=freenx)
02 xres=800x600    07 set default X resolution (default 1024x768)
02 xdepth=16       07 set default X color depth (default 24 bits)
02 zap             07 Allow to kill X with Ctrl + Alt + Backspace
                  (default is not allowed)
02 disablewheel    07 disable mouse wheel and 3 buttons (default enabled)

02 volume=X%       07 set master and pcm volume levels to value (0%-100%)
02 break=XXX       07 Stop at breakpoint (see README file)

Press 02F207 to get more help or 08F1007 to return to main screen

