#!/bin/bash

# get tcos bug info


# SIZE of some files
echo "Size of images:" >&3
du /var/lib/tcos/tftp/initramfs-* /var/lib/tcos/files/usr-* >&3
echo -e "\n" >&3


# /etc/tcos/modules
if [ -f /etc/tcos/modules ]; then 
  echo -e "\nThis is /etc/tcos/modules:\n" >&3
  cat /etc/tcos/modules >&3
else
  echo -e "\nNo /etc/tcos/modules file\n" >&3
fi


