#!/bin/sh
# -------
# File:        session-cmd-send
# Description: session-cmd frontend
# Author:      Luis Garcia Gisbert <garcia_luigis@gva.es>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

LIB_FILE="/usr/lib/tcos/session-cmd-common.sh"
[ -r "$LIB_FILE" ] || exit 1
. ${LIB_FILE}

DATA="$@"
if [ "$1" ] ; then
   for SOCKET in $(list_sockets) ; do
      hose localhost "$SOCKET" --unix --out sh -c "echo $DATA" 2>/dev/null || true
   done
fi
exit 0
