#!/bin/sh
# -------
# File:        session-cmd-exec
# Description: session-cmd backend
# Author:      Luis Garcia Gisbert <garcia_luigis@gva.es>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------


set -e

. /etc/tcos/tcos.conf
. ${TCOS_DIR}/tcos-generation-functions.sh

# title of popup
TITLE="TCOS"

# icon to show in popup
ICON_FILE="/usr/share/pixmaps/tcos-icon-32x32.png"

# timeout for popup (in seconds)
LOGOUT_TIMEOUT=20

# message to show in popup (FIXME i18n)
LOGOUT_MESSAGE="Session will close in $LOGOUT_TIMEOUT seconds"

if [ -d /etc/tcos/conf.d/ ]; then
  for file in /etc/tcos/conf.d/session-cmd*; do
    . $file
  done
fi


MESSAGE_CMD="notify-send -u normal -t $(($LOGOUT_TIMEOUT * 1000)) -i ${ICON_FILE} {$TITLE}"


message(){
   $MESSAGE_CMD "$1" 2>/dev/null
}

socket_basename(){
   echo "$(id -un)"
}

case $1 in
   MESSAGE)
      shift
      if [ "$1" ] ; then
         message "$*"
      fi
      ;;
   LOGOUT)
      message "$LOGOUT_MESSAGE"
      sleep $LOGOUT_TIMEOUT
      if [ `ps -U $(socket_basename) | grep -c -e "ksmserver" -e "start_kdeinit"` -eq 2 ];then
          dcop ksmserver default logout 0 -1 -1
      else
          gnome-session-save --kill --silent
      fi
      ;;
   OPEN)
      shift
      if [ "$1" ] ; then
         [ -x /usr/bin/gnome-open ] && gnome-open "$*" 2>/dev/null
      fi
      ;;
esac
exit 0
