#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


quiet=n


. /scripts/functions
# if break=sqmount STOP here
maybe_break hdd


. /conf/tcos.conf
. /conf/tcos-run-functions




# check if we are booting from HD / USB
_INITRD=$(read_cmdline_var "initrd" "")
if [ "$_INITRD" = "initrd.gz" ]; then
   # booting from hdd, use usr.squashfs from HDD if exists
   mkdir -p /mnt/tmp

   for part in $(grep -e ext3 -e vfat /etc/fstab| awk '{print $1":"$3}'); do
     device=$(echo $part | awk -F":" '{print $1}')
     fs=$(echo $part | awk -F":" '{print $2}')
     mount -t${fs} ${device} /mnt/tmp

     if [ -f /mnt/tmp/usr.squashfs ]; then
       USR_SQUASH=/mnt/tmp/usr.squashfs
       _log "SQMOUNT found usr.squashfs in $device "
       break
     elif [ -f /mnt/tmp/usr-$(uname -r).squashfs ]; then
       USR_SQUASH=/mnt/tmp/usr-$(uname -r).squashfs
       _log "SQMOUNT found usr-$(uname -r).squashfs in $device "
       break
     else
       umount /mnt/tmp
     fi
   done
fi





##############################################


update_progress 5

exit 0

