#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


quiet=n


. /scripts/functions
# if break=httpfs STOP here
maybe_break httpfs


. /conf/tcos.conf
. /conf/tcos-run-functions



if [ -d /usr/share ]; then
  # we have mounted /usr/share with other method
  exit 0
fi


if [ ! -x /bin/httpfs ]; then
  # no httpfs support
  exit 0
fi

# check for url
HTTP_SQUASHFS=$(read_cmdline_var "httpfs" "")
if [ "${HTTP_SQUASHFS}" = "" ]; then
  #log_begin_msg "Warning NO httpfs var found"
    #panic "Error http needed $(read_server "tftp-server")"
    #FS1='(initramfs) ' exec /bin/sh </dev/console >/dev/console 2>&1
    exit 0
  #log_end_msg
fi


modprobe fuse

# move /bin/mount and make a wrapper
mv /bin/mount /bin/mount.orig
cat << EOF > /bin/mount
#!/bin/sh

if [ \$(echo \$@| grep -c httpfs) != 0 ]; then
  /opt/bin/mount \$@
else
  /bin/mount.orig \$@
fi
EOF
chmod +x /bin/mount

log_begin_msg "Using HTTPFS to mount squash"
  /bin/httpfs ${HTTP_SQUASHFS} /mnt/tmp
log_end_msg $?



update_progress 5

exit 0

