#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

quiet=n

. /scripts/functions
# if break=download_settings STOP here
maybe_break download_settings

. /conf/tcos.conf
. /conf/tcos-run-functions

MYIP=$(grep 'fixed-address' /var/lib/dhcp/dhclient.leases | head -1| awk '{print $2}' | sed s/";"//g)

log_begin_msg "Download personalized settings ${MYIP}.conf"
  download_file /tcos/conf/${MYIP}.conf /conf/mysettings.conf
log_end_msg $?


update_progress 2


exit 0
