#!/bin/sh
#

# new header not using prereqs
if [ "$1" = "prereqs" ]; then
  echo ""
  exit 0
fi


# fixme, don't work as expected
exit 0

quiet=n
. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions

log_begin_msg "Setting clock based on hardware clock"
  hwclock --localtime --hctosys
log_end_msg $?

exit 0
