#!/bin/sh
#

# new header not using prereqs
if [ "$1" = "prereqs" ]; then
  echo ""
  exit 0
fi


quiet=n
. /conf/tcos.conf

[ -x /sbin/startacpid ] && /sbin/startacpid > /var/log/acpid.log 2>&1

exit 0
