#!/bin/sh
# 
if [ "$1" = "prereqs" ]; then
  exit 0
fi

quiet=n

. /scripts/functions
# if break=ldconfig STOP here
maybe_break ldconfig


. /conf/tcos.conf
. /conf/tcos-run-functions


# update lib cache
log_begin_msg "Updating lib cache"
 /usr/sbin/ldconfig >> /tmp/initramfs.debug 2>&1 &
log_end_msg $?

# needed for ssh login
grep ^export /conf/tcos.conf > /root/.profile

# mount /dev/shm
# if not mounted
# this causes to break browsers and italc
mkdir -p /dev/shm
mount -t tmpfs shmfs /dev/shm >>/tmp/initramfs.debug 2>&1

# italc 1.0.0 new version
if [ -x /sbin/startica ]; then
  ln -s /sbin/startica /sbin/startivs
fi


if [ -z "$(which Xorg)" ]; then
  _log "LDCONFIG Xorg not found"
  log_failure_msg "Xorg not found"
  log_end_msg 1
  exit 0
fi



 _log "LDCONFIG Updating links in Xorg 7.x mode"
 [ ! -e /usr/lib/libGLcore.so.1 -a -e /usr/lib/libGLcore.so ] && ln -sf /usr/lib/libGLcore.so /usr/lib/libGLcore.so.1
 [ ! -e /usr/lib/libGL.so.1 -a -e /usr/lib/libGL.so.1.2 ] && ln -sf /usr/lib/libGL.so.1.2 /usr/lib/libGL.so.1
 [ ! -e /usr/lib/libGL.so -a -e /usr/lib/libGL.so.1 ] && ln -sf /usr/lib/libGL.so.1 /usr/lib/libGL.so
 [ ! -e /usr/lib/libGLU.so.1 -a -e /usr/lib/libGLU.so ] && ln -sf /usr/lib/libGLU.so /usr/lib/libGLU.so.1
 mkdir -p /usr/share/X11/
 ln -s /etc/X11/rgb.txt /usr/share/X11/rgb.txt
 ln -s /usr/share/X11/xkb /etc/X11/xkb
 mkdir -p /usr/X11R6 >> /tmp/initramfs.debug 2>&1
 ln -s /usr/bin /usr/X11R6/bin >> /tmp/initramfs.debug 2>&1

 mkdir -p /var/lib/xkb
 ln -s /var/lib/xkb     /etc/X11/xkb/compiled
 ln -s /usr/bin/xkbcomp /etc/X11/xkb/xkbcomp

 # make links in keymap rules
    [ ! -e /usr/share/X11/xkb/rules/xfree86 ] &&\
	 ln -s /usr/share/X11/xkb/rules/base /usr/share/X11/xkb/rules/xfree86
    [ ! -e /usr/share/X11/xkb/rules/xfree86.lst ] &&\
	 ln -s /usr/share/X11/xkb/rules/base.lst /usr/share/X11/xkb/rules/xfree86.lst
    [ ! -e /usr/share/X11/xkb/rules/xfree86.xml ] &&\
	 ln -s /usr/share/X11/xkb/rules/base.xml /usr/share/X11/xkb/rules/xfree86.xml

    [ ! -e /usr/share/X11/xkb/rules/xorg ] &&\
	 ln -s /usr/share/X11/xkb/rules/base /usr/share/X11/xkb/rules/xorg
    [ ! -e /usr/share/X11/xkb/rules/xorg.lst ] &&\
	 ln -s /usr/share/X11/xkb/rules/base.lst /usr/share/X11/xkb/rules/xorg.lst
    [ ! -e /usr/share/X11/xkb/rules/xorg.xml ] &&\
	 ln -s /usr/share/X11/xkb/rules/base.xml /usr/share/X11/xkb/rules/xorg.xml


exit 0
