#!/bin/sh
# 

# Adapt /etc/init.d/915resolution to work with TCOS
# Copyright Rubén Gómez Antolí <listas at mucharuina [.] com>


PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


quiet=n
. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions

# if break=intel STOP here
maybe_break intel



PROG915=/usr/bin/915resolution
VBETOOL=/usr/bin/vbetool

test -x $PROG915 || exit 0

#
# Include 915resolution defaults if available
if [ -f /etc/default/915resolution ] ; then
     . /etc/default/915resolution
fi


auto_select_modes()
{

    if [ ! -x "$VBETOOL" ] || ! panelsize=$($VBETOOL vbefp panelsize) ; then
        _log "*** Your 915resolution was not automatically configured! ***"
        _log "Please read /usr/share/doc/915resolution/README.Debian then define"
        _log "MODE, XRESO, and YRESO manually in /etc/default/915resolution ."
        _log "For now a default will be set, which might be inappropiate."
        XRESO=1024
        YRESO=768
    fi


    # If the native panel-size is already in the BIOS mode list, we
    # don't have to do anything, yippee!
    bios_list=$($PROG915 -l)
    if echo "$bios_list" | grep -q "^Mode .* $panelsize" ; then
        _log 'Correct panel-size is already listed, skipping'
        return
    fi

    # For want of a better approach to selecting modelines for stealing;...
    # this expression grabs us the highest *numbered* mode in each
    # bit-depth that the BIOS already lists.
    #
    # An argument for using the highest mode-number, rather than the
    # highest resolution is that if we've already reprogrammed the
    # mode to be a lower resolution it will no longer be the highest.
    # If this has changed over a suspend cycle, that consequences
    # might not be so good.  -Paul Sladen
    target_modes=$(echo "$bios_list" | awk '/^Mode [^T]/{sub(",","",\$4); print $5,$4,$2}' | tac | sort -n -u | cut -d' ' -f3)

    for m in $target_modes ; do
        # The 'tr' converts '1024x768' -> '1024' '768'
        # and the bitdepth is missed off because we have one of each depth
        $PROG915 $m $(echo $panelsize | tr x ' ')
    done
}

if [ "$MODE" = "auto" ] ; then
    auto_select_modes
else
    $PROG915 $MODE $XRESO $YRESO $BIT
fi


# FIXME
# Force create xorg.conf with configurexorg ?
# configurexorg --rres=${XRESO}x${YRESO} --newsettings --xdriver=i810 --outputfile=/etc/X11/xorg.conf 2>> /tmp/initramfs.debug


update_progress

exit 0

