#!/bin/sh
# 
if [ "$1" = "prereqs" ]; then
  exit 0
fi

quiet=n
. /conf/tcos.conf

[ "$TCOS_XORG_VIDEO_DRIVER" = "fullauto" ] && exit 0
[ "$TCOS_XORG_VIDEO_DRIVER" = "xorgauto" ] && exit 0

test_intel=0
test_intel=$(get_vga_vendor 8086)

if [ -e /usr/lib/xorg/modules/drivers/intel_drv.so ]  && [ "$test_intel" = "1" ]; then
  # force intel driver (intel don't like VESA)
  configurexorg --newsettings --xdriver=intel
fi







exit 0

