#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


quiet=n


. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions

. /bin/set-limits

# rewrite /etc/fstab from NFS
if [ "$(cat /tmp/less_ram)" != "0" ]; then
  export NO_UDEV=1
  /scripts/tcos-top/50fstab
  unset NO_UDEV
fi


if [ ${TCOS_USB} ]; then
 MODULES="scsi_mod sd_mod sr_mod isofs vfat floppy usbcore ehci-hcd ohci-hcd uhci-hcd usb-storage"
 log_begin_msg "Loading usb and floppy modules"
   for mod in ${MODULES}; do
     _log "INITTCOS Loading module ${mod}"
     modprobe -q $mod >> /tmp/initramfs.debug 2>&1 &
   done
 log_end_msg 0
else
 _log "INITTCOS usb support disabled"
fi



# if break=ltspfs STOP here
maybe_break ltspfs

# DOCUMENTME noltspfs | disable ltspfs daemon
noltspfs=$(read_cmdline_var "noltspfs" "0")
if [ ${noltspfs} = 1 ]; then
  _log "LTSPFS ltspfs disabled from cmdline"
  exit 0
fi

###################################################
# http://wiki.ltsp.org/twiki/bin/view/Ltsp/LtspFS #
###################################################

if [ "$TCOS_REMOTEFS" = "ltspfs" ]; then
 if [ "$(which ltspfsd)" ] ; then
  # start ltspfsd daemon
  log_begin_msg "Start ltspfs daemon"
  _log "LTSPFS Starting ltspfs daemon"
      # AUTH works ok
      ltspfsd 
  log_end_msg $?
 fi
fi # end of TCOS_REMOTEFS=ltspfs



if [ "$TCOS_REMOTEFS" = "shfs" ]; then
  log_begin_msg "Adding SHFS filesystem user"
   # create shfs user, change pass and allow connect throught ssh
   #root:x:0:0:root:/root:/bin/bash
   echo "shfs:x:1000:1000::/media/autofs:/bin/sh" >> /etc/passwd
   echo "shfs:!:13287:0:99999:7:::" >> /etc/shadow
   echo "shfs:x:1000:" >> /etc/group
   echo "shfs:shfs" | chpasswd >/dev/null 2>&1
   chown shfs:root /media/autofs >/dev/null 2>&1
  log_end_msg $?
fi

update_progress

exit 0
