#!/bin/sh
# 

quiet=n


. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions

. /bin/set-limits

# rewrite /etc/fstab from NFS
if [ "$(cat /tmp/less_ram)" != "0" ]; then
  export NO_UDEV=1
  /scripts/tcos-top/50fstab
  unset NO_UDEV
fi

nodevices=$(read_cmdline_var "nodevices" "0") 
if [ ${nodevices} = 1 ]; then 
  _log "Devices disabled from cmdline" 
  exit 0 
fi


if [ ${TCOS_USB} ]; then
 # load floppy from /lib/extramodules
 [ -e /lib/extramodules/ide-floppy.ko ] && insmod /lib/extramodules/ide-floppy.ko &
 [ -e /lib/extramodules/floppy.ko ] && insmod /lib/extramodules/floppy.ko &

 MODULES="scsi_mod sd_mod sr_mod isofs vfat usbcore ehci-hcd ohci-hcd uhci-hcd usb-storage"
 log_begin_msg "Loading usb modules"
   for mod in ${MODULES}; do
     _log "INITTCOS Loading module ${mod}"
     modprobe -q $mod >> /tmp/initramfs.debug 2>&1 &
   done
 log_end_msg 0
else
 _log "INITTCOS usb support disabled"
fi



# if break=ltspfs STOP here
maybe_break ltspfs

# DOCUMENTME noltspfs | disable ltspfs daemon
noltspfs=$(read_cmdline_var "noltspfs" "0")
if [ ${noltspfs} = 1 ]; then
  _log "LTSPFS ltspfs disabled from cmdline"
  exit 0
fi

###################################################
# http://wiki.ltsp.org/twiki/bin/view/Ltsp/LtspFS #
###################################################

if [ "$TCOS_REMOTEFS" = "ltspfs" ]; then
 if [ "$(which ltspfsd)" ] ; then
  # start ltspfsd daemon
  log_begin_msg "Start ltspfs daemon"
  _log "LTSPFS Starting ltspfs daemon"
      # configure ltspfsd with noauth when starting bootchartd
      if grep -q bootchartd /proc/cmdline ; then
          ltspfsd -a
      else
          # AUTH works ok
          ltspfsd 
      fi
  log_end_msg $?
 fi
fi # end of TCOS_REMOTEFS=ltspfs



update_progress

exit 0
