#!/bin/sh
#

PREREQ=""

prereqs() 
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

quiet=n




if [ -x /usr/sbin/listener-daemon.sh ]; then
   /usr/sbin/listener-daemon.sh > /var/log/listener-daemon.log 2>&1 &
fi

exit 0
