#!/bin/sh
#

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

quiet=n
. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions


# if break=xmlrpc STOP here
maybe_break xmlrpc

# DOCUMENTME noxmlrpc | disable tcosxmlrpc daemon
noxmlrpc=$(read_cmdline_var "noxmlrpc" "0")
if [ ${noxmlrpc} = 1 ]; then
  _log "START-XMLR-PC xmlrpc disabled from cmdline"
  exit 0
fi


# start daemon
log_begin_msg "Starting tcosxmlrpc server"
  _log "START-XML-RC starting startxmlrpc...."
  startxmlrpc &
log_end_msg



# start daemon
log_begin_msg "Starting httpd server"
  _log "HTTPD starting starthttpd...."
  starthttpd.sh &
log_end_msg


exit 0

