#!/bin/sh
#
if [ "$1" = "prereqs" ]; then
  exit 0
fi

quiet=n
. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions


# if break=xmlrpc STOP here
maybe_break xmlrpc

# DOCUMENTME noxmlrpc | disable tcosxmlrpc daemon
noxmlrpc=$(read_cmdline_var "noxmlrpc" "0")
if [ ${noxmlrpc} = 1 ]; then
  _log "START-XMLR-PC xmlrpc disabled from cmdline"
  exit 0
fi


# start daemon
log_begin_msg "Starting tcosxmlrpc server"
  _log "START-XMLRCP starting startxmlrpc...."
  startxmlrpc &
log_end_msg $?



exit 0

