#!/bin/sh
# 
if [ "$1" = "prereqs" ]; then
  exit 0
fi

quiet=n

. /scripts/functions
. /conf/tcos-run-functions


# try to exec installer
INSTALLER=$(read_cmdline_var "installer" "0")

# try to exec installer-update
INSTALLER_UPDATE=$(read_cmdline_var "installer-update" "0")

if [ "${INSTALLER}" = "1" ]; then
   kill_usplash
   chvt 1
   # launch installer
   #clear
   /sbin/installer.sh
   echo ""
   echo "Installer done. You can reboot now or connect server."
   echo ""
   echo "    for reboot/poweroff   exec => reboot poweroff"
   echo "    for connect to server exec => startremotex"
   echo ""
   sh
elif [ "${INSTALLER_UPDATE}" = "1" ]; then
   kill_usplash
   chvt 1
   # launch installer
   #clear
   /sbin/installer.sh --update
   echo ""
   echo "Installer update done. You can reboot now or connect server."
   echo ""
   echo "    for reboot/poweroff   exec => reboot poweroff"
   echo "    for connect to server exec => startremotex"
   echo ""
fi



exit 0
