#!/bin/sh
# 

quiet=n

. /conf/tcos.conf

if [ -z "$TCOS_NTPDATE" ]; then
   exit 0
fi


/usr/bin/ntpdate $TCOS_NTPDATE_SERVER >> /tmp/initramfs.debug 2>&1
if [ $? = 0 ]; then
  # save clock in BIOS
  hwclock --systohc >> /tmp/initramfs.debug 2>&1
fi


exit 0

