#!/bin/sh
# 
if [ "$1" = "prereqs" ]; then
  exit 0
fi

quiet=n

. /conf/tcos.conf
. /scripts/functions
. /conf/tcos-run-functions

. /bin/set-limits

if [ $TCOS_PRINTER ]; then

  LP=""
  [ -e /dev/lp0 ] && LP=/dev/lp0
  [ -e /dev/lp1 ] && LP=/dev/lp1
  [ -e /dev/usblp0 ] && LP=/dev/usblp0
  [ -e /dev/usb/lp0 ] && LP=/dev/usb/lp0

  if [ "${LP}" = "" ]; then exit 0; fi

  if [ -e /usr/bin/p910nd ]; then

     mkdir -p /var/lock/p910nd
     /usr/bin/p910nd -f $LP > /var/log/p910nd.log 2>&1 &

  fi


fi

exit 0
