#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

quiet=n

. /conf/tcos.conf
. /scripts/functions
. /conf/tcos-run-functions

if [ $TCOS_PRINTER ]; then

  [ -e /dev/lp0 ] && LP=/dev/lp0
  [ -e /dev/lp1 ] && LP=/dev/lp1
  [ -e /dev/usblp0 ] && LP=/dev/usblp0

  if [ -e /usr/bin/lp_server ]; then

     /usr/bin/lp_server -d $LP -r tcos-server > /var/log/lp_server.log 2>&1 &

  elif [ -e /usr/bin/print_server ]; then

     /usr/bin/print_server $LP > /var/log/print_server.log 2>&1 &

  fi


fi

exit 0
