#!/bin/sh
# 

PREREQ="01download_settings 05inittcos 10ldconfig 20autofs 30devices 40initsound 50freespace 60installer 70startx"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

quiet=n

. /scripts/functions
. /conf/tcos-run-functions



clear
echo ""
echo ""  
echo "Press enter to activate this console..."
read enter
export PS1="($(hostname)-$(whoami)) # "
sh




exit 0
