#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

quiet=n


. /scripts/functions
. /conf/tcos.conf
. /conf/tcos-run-functions

create_links() {
 [ ! -x /bin/$1 ] && ln -s /bin/busybox /bin/$1
}


create_links "date"
create_links "bash"
create_links "tftp"
create_links "awk"
create_links "dirname"
create_links "chown"
create_links "wc"
create_links "head"
create_links "whoami"
create_links "swapon"
create_links "swapoff"
create_links "dmesg"
create_links "route"
create_links "run-parts"
create_links "killall"
create_links "which"
create_links "pidof"
create_links "syslogd"
create_links "logger"

# start syslogd (busybox embeded)
busybox syslogd 2>/dev/null 

if [ $? != 0 ]; then
  # create a fuck logger
  rm -f /bin/logger
  cat << EOF > /bin/logger
#!/bin/sh

echo "[\$(date +'%d/%m/%y %H:%M:%S')] \$2: \$3" >> /var/log/messages
EOF
  chmod +x /bin/logger
fi


# hack for ubuntu udev

while [ ! -d /sys/class/net/eth0 ]; do
     [ -x /sbin/udevtrigger ] && /sbin/udevtrigger
     [ -x /sbin/udevplug ]    && /sbin/udevplug
     sleep 1
done



exit 0
