.TH tcos-standalone 1 "Nov 29, 2007" "tcos-standalone man page"

.SH NAME
tcos-standalone \- Python GTK2 gui that allow to enable or disable tcos-standalone mode.

.SH DESCRIPTION

.PP
\fBtcos-standalone\fP is a small python GUI  to enable or disable tcos-standalone mode


tcos-standalone edit /etc/default/tcos-standalone and creates /etc/tcospasswd

.SH OPTIONS
.B [no options]
 With no options will run in normal mode.

.B --help
 Some usage help about tcos-standalone

.B --debug
 Show verbose output when running

.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Homepage: http://www.tcosproject.org

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
